### ISSUE TITLE
Some remark about dunn index

### ISSUE THREAD

**Issue by jungpilyu** [trustyai-explainability/community#19]
Sorry for my comments which have nothing to do with this repository.
Just I looked for a mean to communicate with you and found this repository where your latest trace is found.

I came across your page about [dunn-index](https://ruivieira.dev/dunn-index).
After having taken look at the implementation of dunn index there, I found some typos.

- First of all, the following code should be changed for the correct calculation of `δ(ck, cl)`.
```python
clus0 = prediction.loc[prediction.pred == 0]
clus1 = prediction.loc[prediction.pred == 1]
clus2 = prediction.loc[prediction.pred == 2]
```
with
```python
clus0 = prediction.loc[prediction.pred == 0, ['x1,'x2']]
clus1 = prediction.loc[prediction.pred == 1, ['x1,'x2']]
clus2 = prediction.loc[prediction.pred == 2, ['x1,'x2']]
```
- The main code should be changed too. If not, `np.min(δs)` wrongly produces 1.0.

**original code**
```python
def dunn(k_list):
    δs = np.ones([len(k_list), len(k_list)])
    Δs = np.zeros([len(k_list), 1])
    l_range = list(range(0, len(k_list)))
    for k in l_range:
        for l in (l_range[0:k]+l_range[k+1:]):
            δs[k, l] = δ(k_list[k], k_list[l])
            Δs[k] = Δ(k_list[k])
            di = np.min(δs)/np.max(Δs)
    return di
```
**changed code**
```python
def dunn(k_list):
    δs = np.ones([len(k_list), len(k_list)])*np.inf
    Δs = np.zeros([len(k_list), 1])
    l_range = list(range(0, len(k_list)))
    for k in l_range:
        for l in (l_range[0:k]+l_range[k+1:]):
            δs[k, l] = δ(k_list[k], k_list[l])
            Δs[k] = Δ(k_list[k])
            di = np.min(δs)/np.max(Δs)
    return di
```
- In addition, it would be better for the sake of speedy execution.

**more efficient code**
```python
def dunn(k_list):
    δs = np.ones([len(k_list), len(k_list)])*np.inf
    Δs = np.zeros([len(k_list), 1])
    l_range = list(range(0, len(k_list)))
    for k in l_range:
        Δs[k] = Δ(k_list[k])
        for l in l_range[k+1:]:
            δs[k, l] = δ(k_list[k], k_list[l])
        di = np.min(δs)/np.max(Δs)
    return di
```
You can close this issue as soon as you read.

**Comment by ruivieira** [comment]
Hi @jungpilyu. thank you for the correction. 

However this relates to my personal blog, and this repository is for issues related to the TrustyAI project and community. As such I will close it.

**Comment by ruivieira** [comment]
@jungpilyu Finally got around to fix this, thanks for the heads up.

New version: https://ruivieira.dev/dunn-index.html
